application: psinque
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: off

# Later, to receive emails, we will need to add:
# inbound_services:
# - mail

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
- name: lxml
  version: latest
  
handlers:
# Start pages
- url: /
  script: StartPage.app    # checks if the user is logged in and redirects
  secure: optional
- url: /login
  script: StartPage.app    # user not logged in

# User profile viewing and editing
- url: /mycard/([^/]+)
  script: MyCard.app
- url: /uploadphoto
  script: MyCard.app
- url: /uploadphotopost
  script: MyCard.app
- url: /serveimageblob/([^/]+)?
  script: MyCard.app

# Groups
- url: /groups/([^/]+)
  script: Groups.app

# Psinques
- url: /psinques/([^/]+)
  script: Psinques.app
# - url: /outgoing/([^/]+)
#   script: Outgoing.app
# - url: /decisions/([^/]+)
#   script: Psinques.app

# User settings
- url: /settings
  script: Settings.app
- url: /savesettings
  script: Settings.app

# Static pages
- url: /about
  script: StaticPages.app
  
# Static files
- url: /javascripts
  static_dir: javascripts
- url: /stylesheets
  static_dir: stylesheets
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# CardDAV
- url: /.well-known/carddav
  secure: optional
  script: CardDAV.app
- url: /carddav/.*
  secure: optional
  script: CardDAV.app

# Error handling
- url: /.*
  script: NotFound.app
