application: psinque
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: off

libraries:
- name: jinja2
  version: latest
  
handlers:
# Start pages
- url: /
  script: StartPage.py    # checks if the user is logged in and redirects
  secure: optional
- url: /login
  script: StartPage.py    # user not logged in

# User profile viewing and editing
- url: /profile
  script: MyCard.py    # user logged in, shows the visiting card
- url: /editprofile
  script: MyCard.py
- url: /submitprofile
  script: MyCard.py
- url: /uploadphoto
  script: MyCard.py
- url: /uploadphotopost
  script: MyCard.py
- url: /serveimageblob/([^/]+)?
  script: MyCard.py

# Contacts
- url: /contacts
  script: Contacts.py
- url: /searchcontacts
  script: Contacts.py
- url: /addcontact
  script: Contacts.py

# Notifications
- url: /notifications
  script: Notifications.py
- url: /changerelationship    # AJAX queries
  script: Notifications.py

# Under construction
- url: /groups
  script: UnderConstruction.py

# User settings
- url: /settings
  script: Settings.py
- url: /savesettings
  script: Settings.py

# Static pages
- url: /about
  script: StaticPages.py
  
# Static files
- url: /stylesheets
  static_dir: stylesheets
- url: /javascripts
  static_dir: javascripts
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# CardDAV
- url: /carddav/*
  secure: always
  script: CardDAV.py

# Error handling
- url: /.*
  script: NotFound.py
