application: psinque
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
# Start pages
- url: /
  script: StartPage.py    # checks if the user is logged in and redirects
- url: /login
  script: StartPage.py    # user not logged in

# User profile viewing and editing
- url: /profile
  script: Profile.py    # user logged in, shows the visiting card
- url: /editprofile
  script: Profile.py
- url: /submitprofile
  script: Profile.py
- url: /uploadphoto
  script: Profile.py
- url: /uploadphotopost
  script: Profile.py
- url: /serveimageblob/([^/]+)?
  script: Profile.py

# Contacts
- url: /contacts
  script: Contacts.py
- url: /searchcontacts
  script: Contacts.py
- url: /addcontact
  script: Contacts.py

# Under construction
- url: /notifications
  script: UnderConstruction.py
- url: /groups
  script: UnderConstruction.py

# User settings
- url: /settings
  script: UserSettings.py
- url: /savesettings
  script: UserSettings.py

# Static pages
- url: /about
  script: StaticPages.py
  
# Static files
- url: /stylesheets
  static_dir: stylesheets
- url: /javascripts
  static_dir: javascripts
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
# Error handling
- url: /.*
  script: NotFound.py
