application: psinque
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: off
# - admin_redirect: on

# Later, to receive emails, we will need to add:
# inbound_services:
# - mail

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
- name: lxml
  version: latest
  
handlers:
# Start pages
- url: /
  script: Countdown.app
- url: /reallandingforsecrettesters
  script: StartPage.app    # checks if the user is logged in and redirects
  secure: optional

# OpenID login handler
- url: /_ah/login_required
  script: Login.app
  
# Static pages
- url: /static/([^/]+)
  script: StaticPages.app
  secure: optional

# Profile
- url: /profile/([^/]+)
  script: Profile.app
  login: required
- url: /uploadphoto
  script: Profile.app
- url: /uploadphotopost
  script: Profile.app
- url: /serveimageblob/([^/]+)?
  script: Profile.app

# Personas
- url: /personas/([^/]+)
  script: Personas.app
  login: required

# Psinques
- url: /psinques/([^/]+)
  script: Psinques.app
  login: required

# User settings
- url: /settings/([^/]+)
  script: Settings.app
  login: required

# Custom admin console pages
- url: /admin/([^/]+)
  script: Admin.app
  login: admin

# Static files
- url: /javascripts
  static_dir: javascripts
- url: /stylesheets
  static_dir: stylesheets
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /favicon_128.ico
  static_files: static/favicon_128.ico
  upload: static/favicon_128.ico
- url: /favicon.svg
  static_files: static/favicon.svg
  upload: static/favicon.svg

# CardDAV
- url: /.well-known/carddav
  secure: optional
  script: CardDAV.app
- url: /carddav/.*
  secure: optional
  script: CardDAV.app

# Web crawlers
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

# Error handling
- url: /.*
  script: NotFound.app
  
# Custom admin console pages (DOES NOT WORK: THERE IS SOME ISSUE WITH login: admin)
# admin_console:
#   pages:
#   - name: User profiles
#     url: /admin/userprofile
